import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#1b1b1b",
        "surface-container-low": "#f0f3ff",
        "surface-container-highest": "#dce2f3",
        primary: "#000000",
        "primary-container": "#1b1b1b",
        "inverse-primary": "#c6c6c6",
        "surface-bright": "#f9f9ff",
        "inverse-on-surface": "#ebf1ff",
        "tertiary-fixed-dim": "#c6c6c6",
        "surface-variant": "#dce2f3",
        "secondary-fixed": "#ffdbca",
        "on-secondary": "#ffffff",
        secondary: "#9d4300",
        "secondary-container": "#fd761a",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-high": "#e2e8f8",
        "surface-tint": "#5e5e5e",
        "on-primary": "#ffffff",
        "outline-variant": "#cfc4c5",
        "on-primary-fixed": "#1b1b1b",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        surface: "#f9f9ff",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#1b1b1b",
        error: "#ba1a1a",
        "primary-fixed-dim": "#c6c6c6",
        tertiary: "#000000",
        "on-tertiary-container": "#848484",
        "on-tertiary-fixed-variant": "#474747",
        "on-primary-fixed-variant": "#474747",
        "on-secondary-fixed-variant": "#783200",
        "inverse-surface": "#2a313d",
        "surface-dim": "#d3daea",
        "on-surface": "#151c27",
        "on-primary-container": "#848484",
        "primary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#ffb690",
        "on-secondary-fixed": "#341100",
        "error-container": "#ffdad6",
        "on-background": "#151c27",
        "on-secondary-container": "#5c2400",
        "surface-container": "#e7eefe",
        "on-surface-variant": "#4c4546",
        outline: "#7e7576",
        background: "#f9f9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "32px",
        unit: "4px",
        "container-padding": "20px",
        "stack-gap": "12px",
        gutter: "16px",
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md-mobile": ["Geist", "sans-serif"],
        "status-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-lg": [
          "18px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "headline-md-mobile": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "status-sm": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0em", fontWeight: "600" },
        ],
        "display-lg": [
          "40px",
          { lineHeight: "44px", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
